/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;

/**
 *
 * @author Leto
 */
public class GamePanel extends javax.swing.JPanel {

    private Control ctr;

    /**
     * Creates new form GamePanel
     */


    public GamePanel() {
        initComponents();
        ctr = new Control();
    }

    public void paintComponent(Graphics g){
        g.setColor(Color.BLACK);
        g.fillRect(0,0,this.getWidth(), this.getHeight());
        g.setColor(Color.GREEN);
        draw_all_citizen(g);
    }

    private void draw_all_citizen(Graphics g){
        int f_size = ctr.get_families_size();

        for (int i = 0; i < f_size; ++i){
            int c_size = ctr.families.get(i).get_member_count();

            for (int j = 0; j < c_size; ++j){
                g.fillRect(ctr.get_fam_member_x_pos(i, j), ctr.get_fam_member_y_pos(i,j), 2, 2);
                System.out.println("print familie "+ i +" member " + j);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    // End of variables declaration
}
